#!/usr/bin/env bash
#creates a new nginx serve and serves an index.html file

sudo app-get update
sudo app-get install -y ngnix

# Configure nginx to listen on port 80
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
echo '<html><head><title>Hello World!</title></head><body><h1>Hello World!</h1></body></html>' | sudo tee /var/www/html/index.html > /dev/null

# Restart nginx using service command (since systemctl is not allowed)
sudo service nginx restart

# Display the status of nginx
sudo service nginx status
