#!/usr/bin/env bash
#creates a new nginx serve and serves an index.html file

sudo apt-get update
sudo apt-get install -y nginx

sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

echo '<html><head><title>Hello World!</title></head><body><h1>Hello World!</h1></body></html>' | sudo tee /var/www/html/index.html > /dev/null

sudo service nginx restart
sudo service nginx status
