#!/usr/bin/env bash
#creates a new nginx serve and serves an index.html file

sudo apt-get update
sudo apt-get install -y nginx

ufw allow 'Nginx HTTP'

echo 'ALX SCHOOL | sudo tee /var/www/html/redirect.html > /dev/null'

sudo tee /etc/nginx/sites-available/default > /dev/null <<EOT

server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm;
    server_name _;
    location /redirect_me {
        return 301 /redirect.html;
    }
}
EOT

sudo service nginx restart
sudo service nginx status