#!/usr/bin/env bash
#creates a new nginx serve and serves an index.html file

sudo apt-get update
sudo apt-get install -y nginx

ufw allow 'Nginx HTTP'

echo 'ALX SCHOOL | sudo tee /var/www/html/redirect.html > /dev/null'

sudo tee /etc/nginx/sites-available/default > /dev/null

sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://portfolio.derawllings.com permanent;' /etc/nginx/sites-available/default

sudo service nginx restart
sudo service nginx status