#!/usr/bin/env bash
# Display "Best School" 10 times and displays "Hi" for the 9th iteration

a=0

while [ $a -lt 10 ]; do
      echo "Best School"
      if [ $a -eq 8 ]; then
	  echo "Hi"
      fi
      a=$((a+1))
done
